spring.application.name=NauJava
spring.datasource.url=jdbc:postgresql://localhost:5433/java
spring.datasource.username=admin
spring.datasource.password=1q2w3e4r
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
jwt.secret=jwt.secret=Rt8wP3kL9qXz5nY7mBvCdFgHjKlNpQsTuVxZ2b4e6h8jMnQrStUvWxYzAbC5E7G9J1L3N5P7R9T1V3X5Z7B9D1F3H5J7L9M1N3P5R7T9V1X3Z5B7D9F1H3J5L7M9N1P3R5T7V9X1Z3B5D7F9H1J3L5M7N9P1R3

# ??????????? SQL ????????
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ??????????? ??????????
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG

# ??????????? ????????
logging.level.org.springframework.web=DEBUG
logging.level.ru.artem.NauJava=DEBUG

# ???????? Java Melody
javamelody.enabled=true

# URL ??? ???????????
javamelody.init-parameters.monitoring-path=/monitoring

# ????? ? ?????? ??? ???????
javamelody.init-parameters.authorized-users=admin:admin123

# ??? ??????????
javamelody.init-parameters.log=true
javamelody.init-parameters.http-transform-pattern=\\d+
javamelody.init-parameters.storage-directory=./monitoring-data

